### ISSUE TITLE
Single line entry with fullwidth progress

### ISSUE THREAD

**Issue by eftekharian** [eftekharian/convert-to-mp3-webapp#10]
Instead of adding a new line for the "download" and "delete" buttons, let's rename the "cancel" button to "download" when needed. If a new conversion for an old entry is requested, then we can rename it back to "download" again. Instead of the "Delete" button let's have a button floated to the right side with a value of "×".

Instead of having a GIF for progress, let's have a fullwidth progress bar that sticks to the top of each entry. We can have a div element as a progress-bar to be more flexible in terms of styling. 

Also, it makes sense to keep all buttons aligned vertically for all entries. Use the "table" element. 

Note that currently if the filename is too long we have an overflow. Please use "ellipsis" text-overflow to trim the string.

**Comment by OpneMind** [comment]
I dont use gift !!!

**Comment by OpneMind** [comment]
please. dont send multi task in one comment.

thanks

**Comment by OpneMind** [comment]
> Also, it makes sense to keep all buttons aligned vertically for all entries. Use the "table" element.

fixesd

**Comment by OpneMind** [comment]
> Instead of adding a new line for the "download" and "delete" buttons, let's rename the "cancel" button to "download" when needed. If a new conversion for an old entry is requested, then we can rename it back to "download" again. Instead of the "Delete" button let's have a button floated to the right side with a value of "×".

fixed
