### ISSUE TITLE
dealing with unsupported files

### ISSUE THREAD

**Issue by eftekharian** [eftekharian/convert-to-mp3-webapp#18]
If an unsupported file is dropped to the UI, we should have an entry with an error message, instead of ignoring it. Also, note that video files should be able to convert since AudioContext supports them

**Comment by OpneMind** [comment]
Video size usaully very larg this lead to crash browser

**Comment by eftekharian** [comment]
we can warn the user about the possible crash when a new entry is added. Link a message in the entry box.
