### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by eftekharian** [eftekharian/convert-to-mp3-webapp#20]
Please make sure we are localizing the entire page. Example of a nonlocalized element

```html
<button class="coverttomp3btn" data-i18n="Covert">Covert</button>
```

**Comment by OpneMind** [comment]
I do not know how to call your localization after add new element.

**Comment by eftekharian** [comment]
https://github.com/eftekharian/convert-to-mp3-webapp/blob/master/convert-to-mp3/js/localize.js#L157

when a new element is created, use `e.textContent = window.getLocale('key');` inside your JS code. There is no need to rerun for entire page.

**Comment by eftekharian** [comment]
are you done with this issue? This one is still open and we what to start our review on the closed issues.

**Comment by OpneMind** [comment]
> window.getLocale('key');



> https://github.com/eftekharian/convert-to-mp3-webapp/blob/master/convert-to-mp3/js/localize.js#L157
> 
> when a new element is created, use `e.textContent = window.getLocale('key');` inside your JS code. There is no need to rerun for the entire page.

TypeError: window.locales[key] is undefined
