### ISSUE TITLE
video file is not supported

### ISSUE THREAD

**Issue by eftekharian** [eftekharian/convert-to-mp3-webapp#22]
When dropping a WebM video file, the page warns that this filetype is not supported. As we have discussed, the page should accept both audio and video files and warn the user that the page might crash only for huge files "just" before the conversion.

**Comment by eftekharian** [comment]
Please use "confirm" instead of "alert". We should abort if the user wants too. Also make sure all language strings are localized; https://github.com/eftekharian/convert-to-mp3-webapp/commit/a0ff4cb08f260ff47ff6bfc8b8e645f87a911366#diff-d861bc6f8ee6bdfcced845c44ed1abd4R133

**Comment by eftekharian** [comment]
> Please use "confirm" instead of "alert".

Is this one fixed? I dont get any prompt when a large file is dropped.

**Comment by eftekharian** [comment]
> Also make sure all language strings are localized

https://github.com/eftekharian/convert-to-mp3-webapp/blob/5592700c466dd805458b8ae1b1d322de35142d06/convert-to-mp3/js/scripts.js#L28

**Comment by OpneMind** [comment]
this is a gift a can remove it.
eftekharian == حسن ابراهیمی ?

**Comment by OpneMind** [comment]
video supported
