### ISSUE TITLE
wrong conversion parameters?

### ISSUE THREAD

**Issue by eftekharian** [eftekharian/convert-to-mp3-webapp#23]
do a conversion and test with VLC to make sure the conversion parameters are actually applied.

![Screen Shot 2019-08-11 at 11 47 11 AM](https://user-images.githubusercontent.com/48516243/62832922-b3ed5c80-bc25-11e9-920d-a024a02d17fb.png)

**Comment by OpneMind** [comment]
You can convert with other online converter and compare results.
