### ISSUE TITLE
abort current conversion

### ISSUE THREAD

**Issue by eftekharian** [eftekharian/convert-to-mp3-webapp#24]
There doesn't seem to be a button to abort the conversion in the middle of the process. also, what happens if a user presses the convert button multiple times when it is not disabled during the conversion?

**Comment by OpneMind** [comment]
redownload and test again. X abort the conversion in the middle of the process

**Comment by eftekharian** [comment]
Your "X" is not always visible on all window widths.

![Screen Shot 2019-08-12 at 6 49 18 AM](https://user-images.githubusercontent.com/48516243/62847285-f31eba80-bcc4-11e9-838b-f5e7cfccfa29.png)
