### ISSUE TITLE
trim is not possible

### ISSUE THREAD

**Issue by eftekharian** [eftekharian/convert-to-mp3-webapp#25]
With the new UI, it is not possible to trim the audio. Whenever the element is selected, the audio range gets back to the original value. Please make sure to check the UI after fixing an issue.

**Comment by OpneMind** [comment]
Ok, I thought you wanted this

**Comment by eftekharian** [comment]
When a new item is selected from the available ones, the audio range should be updated, but when an item is already selected and the user applies a different range and now asks for conversion, the range should not be updated. In short, you should only update the range when a new item is selected, not when the user clicks on an already selected item.

Normally there is no JS code required for this, you just need to define an `input[type=radio]` for each item and listen on the `onchange` event. When an already selected item is clicked, the `onchanged` is not being called and hence you are not overwriting the user's predefined range.

**Comment by eftekharian** [comment]
still doesnt work. just add two files and switch between them, the range is not updating.

**Comment by OpneMind** [comment]
this is a gift i can remove it
