### ISSUE TITLE
mixing tab and whitespace

### ISSUE THREAD

**Issue by eftekharian** [eftekharian/convert-to-mp3-webapp#27]
Adjust your editor to show invisible chars to prevent tab and whitespace mixture

![Screen Shot 2019-08-11 at 11 47 11 AM](https://user-images.githubusercontent.com/48516243/62833052-e304cd80-bc27-11e9-931f-c3c04c7bc4e0.png)

**Comment by OpneMind** [comment]
?!

**Comment by eftekharian** [comment]
wrong screenshot aparently!
![Screen Shot 2019-08-12 at 6 47 24 AM](https://user-images.githubusercontent.com/48516243/62847226-ae931f00-bcc4-11e9-872b-9f66d72bca73.png)

see the first char of line 15 for instance.
