### ISSUE TITLE
no need for audio element after conversion

### ISSUE THREAD

**Issue by eftekharian** [eftekharian/convert-to-mp3-webapp#3]
There is no need to have a saparate audio element for the converted MP3 file. Just a single one that works with the orignal audio is just fine

**Comment by OpneMind** [comment]
applied

**Comment by eftekharian** [comment]
ref https://github.com/eftekharian/convert-to-mp3-webapp/commit/9fa2589628a6b35af9b289ff1cc2983ac3fbc4c3
