### ISSUE TITLE
ESLint

### ISSUE THREAD

**Issue by eftekharian** [eftekharian/convert-to-mp3-webapp#7]
Please use ESLint to lint your code

![Screen Shot 2019-08-05 at 11 02 36 AM](https://user-images.githubusercontent.com/48516243/62456552-337fb500-b768-11e9-95bb-42ba19ba34d1.png)

**Comment by eftekharian** [comment]
@OpneMind you should close with `fixes #7` instead of `fixes 7`

**Comment by OpneMind** [comment]
fixed

**Comment by OpneMind** [comment]
ok

**Comment by eftekharian** [comment]
refs https://github.com/eftekharian/convert-to-mp3-webapp/commit/6f52d5e388a026c87dfeb59fb9d09f6cd88ad4c1 https://github.com/eftekharian/convert-to-mp3-webapp/commit/ff957719e52a6fedcd1d122987beb563ae068816 https://github.com/eftekharian/convert-to-mp3-webapp/commit/9025b6d626b06ca2ae104fb5a46e55062eef12aa  https://github.com/eftekharian/convert-to-mp3-webapp/commit/7b345dda7c0bc3fbdb90d6d9dee8c1bf45853a88
