### ISSUE TITLE
reference

### ISSUE THREAD

**Issue by eftekharian** [eftekharian/convert-to-mp3-webapp#8]
can you provide the reference for `44`

https://github.com/eftekharian/convert-to-mp3-webapp/blob/df8ec359d49ab96f965f13bd0dc53f2888ff5187/convert-to-mp3/js/audiobuffer-to-wav.js#L27

**Comment by eftekharian** [comment]
encodeBuffer method seems like to accept PCM just fine. There is no need for WAV conversion.

**Comment by OpneMind** [comment]
https://gist.github.com/revolunet/46d4187c3b6f28632a91421c1f2a9fad

**Comment by OpneMind** [comment]
https://github.com/Jam3/audiobuffer-to-wav

**Comment by OpneMind** [comment]
> encodeBuffer method seems like to accept PCM just fine. There is no need for WAV conversion.

encodeBuffer  need Int16array/Int8array then must be conver all type to IntXarray . Convert to wav is best maner. if you know another way with best performanc , please send to me by example

thanks

**Comment by eftekharian** [comment]
you already have the iteration in the WAV transformation, right? https://github.com/eftekharian/convert-to-mp3-webapp/blob/df8ec359d49ab96f965f13bd0dc53f2888ff5187/convert-to-mp3/js/audiobuffer-to-wav.js#L73

**Comment by eftekharian** [comment]
https://github.com/eftekharian/convert-to-mp3-webapp/blob/df8ec359d49ab96f965f13bd0dc53f2888ff5187/convert-to-mp3/js/audiobuffer-to-wav.js#L56

**Comment by OpneMind** [comment]
yes

**Comment by eftekharian** [comment]
So please do not convert to WAV. Just directly pass the PCM data to the encoder

**Comment by OpneMind** [comment]
floatTo16BitPCM 

> encodeBuffer method seems like to accept PCM just fine. There is no need for WAV conversion.

The buffer contains data in the following format: non-interleaved IEEE754 32-bit linear PCM with a nominal range between -1 and +1, that is, 32bits floating point buffer, with each samples between -1.0 and 1.0. If the AudioBuffer has multiple channels,
reference:
https://developer.mozilla.org/en-US/docs/Web/API/AudioBuffer

But encodeBuffer need 16BitPCM ! 16-bit depth stereo is accepted.

**Comment by eftekharian** [comment]
example code:

```JS
/* globals lamejs */

const mp3encoder = new lamejs.Mp3Encoder(channels, sampleRate, bitrate);

const sampleBlockSize = 1152; // can be anything but make it a multiple of 576 to make encoders life easier

const mp3Data = [];
for (let i = 0; i < length; i += sampleBlockSize) {
  console.log('progress', i / length * 100);
  let mp3buf;
  if (channels === 1) {
    const leftChunk = left.subarray(i, i + sampleBlockSize);
    // Convert to required format
    for (let i = 0; i < leftChunk.length; i++) {
      leftChunk[i] = leftChunk[i] * 32767.5;
    }
    mp3buf = mp3encoder.encodeBuffer(leftChunk);
  }
  else {
    const leftChunk = left.subarray(i, i + sampleBlockSize);
    const rightChunk = right.subarray(i, i + sampleBlockSize);
    // Convert to required format
    for (let i = 0; i < leftChunk.length; i++) {
      leftChunk[i] = leftChunk[i] * 32767.5;
      rightChunk[i] = rightChunk[i] * 32767.5;
    }
    mp3buf = mp3encoder.encodeBuffer(leftChunk, rightChunk);
  }
  if (mp3buf.length > 0) {
    mp3Data.push(mp3buf);
  }
}
const mp3buf = mp3encoder.flush();
```

left & right are the direct outputs of our AudioContext

**Comment by OpneMind** [comment]
left & right are the direct outputs of  "lamejs.WavHeader.readHeader(new DataView(audioData))"
no AudioContext.



‌

**Comment by OpneMind** [comment]
My dear friend, I have carefully reviewed all the things you are now discussing.

**Comment by eftekharian** [comment]
I am still not convinced why you are not directly pushing the channel data to the encoder like what I explained. What is the advantage of converting to WAV when we already have the PCM buffer?

**Comment by OpneMind** [comment]
lamejs not accept Audiocontext PCM buffer formation .

https://github.com/zhuker/lamejs/issues/10

**Comment by OpneMind** [comment]
If you can directly (without any change) pass Audiocontext channel data to the encoder. You pay to me only 750000 toman vs 1000000 toman. 25% payment OFF

**Comment by eftekharian** [comment]
Here is a minimal example. Run a server at the root and open in a browser to convert to MP3. Please fix your code by removing the `wave` conversion. 
[basic.zip](https://github.com/eftekharian/convert-to-mp3-webapp/files/3489906/basic.zip)

**Comment by OpneMind** [comment]
OHH. You convert with this loop ;)

`      for (let i = 0; i < leftChunk.length; i++) {
        leftChunk[i] = leftChunk[i] * 32767.5;
        rightChunk[i] = rightChunk[i] * 32767.5;
      }
`

I had already explained  about this !!!!!

but compare this loop with my method, my method performance is better. u can use big file and compare.
In addition, all my manipolation working on converted buffer
(i can change "wav converter" name to "buffer correction")

**Comment by OpneMind** [comment]
Performance analazy again and again ....
Then
hard working on last nighte and:
1- chenge wav convertor with Loop convertor (many change for compatiblety);
2- progrssbar Reduced performance (messaging with worker) -- corrected.
3 4 5 .....
now run faster and beter befor
